import '@/static/globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import FooterNav from '@/components/FooterNav'
import tw from "tailwind-styled-components"

const BodyContainer = tw.div`
    flex flex-col items-center
    w-full h-full flex-1
    bg-shibabrown-100
    overflow-auto 
    scroll-transparent 
    scroll-overlay  
`

const BodyLayout = tw.div`
    flex flex-col justify-center
    w-full max-w-[1600px]
    px-2 lg:px-6
`

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'AH! SHIBA',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Nav />
                <BodyContainer>
                    <BodyLayout>
                        {children}
                        {/* <Footer /> */}
                    </BodyLayout>
                </BodyContainer>
                <FooterNav/>
            </body>
        </html>
    )
}
